# Generated by Django 3.1 on 2020-08-19 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 19, 3, 4, 33, 253305))),
                ('URL', models.URLField(max_length=100)),
            ],
        ),
    ]
